/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2018-04-18T15:17:04.753-04:00
  3.18.0.7
  
  Standalone prediction code with sample test data for GBMModel named gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.1.6:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.1.6:54321/3/Models.java/gbm-a65d8149-cfdc-4f33-bead-5d9456e4a93b > gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b", algorithm="gbm")
public class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Binomial; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 30; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* Time */ null,
    /* V1 */ null,
    /* V2 */ null,
    /* V3 */ null,
    /* V4 */ null,
    /* V5 */ null,
    /* V6 */ null,
    /* V7 */ null,
    /* V8 */ null,
    /* V9 */ null,
    /* V10 */ null,
    /* V11 */ null,
    /* V12 */ null,
    /* V13 */ null,
    /* V14 */ null,
    /* V15 */ null,
    /* V16 */ null,
    /* V17 */ null,
    /* V18 */ null,
    /* V19 */ null,
    /* V20 */ null,
    /* V21 */ null,
    /* V22 */ null,
    /* V23 */ null,
    /* V24 */ null,
    /* V25 */ null,
    /* V26 */ null,
    /* V27 */ null,
    /* V28 */ null,
    /* Amount */ null,
    /* Class */ gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_ColInfo_30.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.9982725143693799,0.001727485630620034};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {0.9982725143693799,0.001727485630620034};

  public gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b() { super(NAMES,DOMAINS,"Class"); }
  public String getUUID() { return Long.toString(-7853760105403411712L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_0.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_1.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_2.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_3.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_4.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_5.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_6.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_7.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_8.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_9.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_10.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_11.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_12.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_13.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_14.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_15.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_16.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_17.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_18.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_19.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_20.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_21.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_22.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_23.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_24.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_25.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_26.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_27.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_28.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_29.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_30.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_31.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_32.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_33.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_34.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_35.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_36.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_37.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_38.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_39.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_40.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_41.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_42.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_43.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_44.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_45.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_46.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_47.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_48.score0(data,preds);
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_49.score0(data,preds);
    preds[2] = preds[1] + -6.359359340922742;
    preds[2] = 1./(1. + Math.min(1e19, Math.exp(-(preds[2]))));
    preds[1] = 1.0-preds[2];
    preds[0] = hex.genmodel.GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.7156849446769096);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b implements java.io.Serializable {
  public static final String[] VALUES = new String[30];
  static {
    NamesHolder_gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_0.fill(VALUES);
  }
  static final class NamesHolder_gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Time";
      sa[1] = "V1";
      sa[2] = "V2";
      sa[3] = "V3";
      sa[4] = "V4";
      sa[5] = "V5";
      sa[6] = "V6";
      sa[7] = "V7";
      sa[8] = "V8";
      sa[9] = "V9";
      sa[10] = "V10";
      sa[11] = "V11";
      sa[12] = "V12";
      sa[13] = "V13";
      sa[14] = "V14";
      sa[15] = "V15";
      sa[16] = "V16";
      sa[17] = "V17";
      sa[18] = "V18";
      sa[19] = "V19";
      sa[20] = "V20";
      sa[21] = "V21";
      sa[22] = "V22";
      sa[23] = "V23";
      sa[24] = "V24";
      sa[25] = "V25";
      sa[26] = "V26";
      sa[27] = "V27";
      sa[28] = "V28";
      sa[29] = "Amount";
    }
  }
}
// The class representing column Class
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_ColInfo_30 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_ColInfo_30_0.fill(VALUES);
  }
  static final class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_ColInfo_30_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
    }
  }
}

class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_0_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[17 /* V17 */] <-2.745134f ? 
         (Double.isNaN(data[12]) || data[12 /* V12 */] <-2.1788788f ? 
             (Double.isNaN(data[14]) || data[14 /* V14 */] <-2.7991297f ? 
                 (data[26 /* V26 */] <-0.2262134f ? 
                     (data[0 /* Time */] <33523.5f ? 
                        13.633818f : 
                        50.984913f) : 
                     (data[4 /* V4 */] <1.202462f ? 
                        35.58491f : 
                        55.52149f)) : 
                 (data[9 /* V9 */] <-2.2079842f ? 
                    40.49166f : 
                     (data[21 /* V21 */] <0.85049516f ? 
                        17.29623f : 
                        -0.10017305f))) : 
             (data[3 /* V3 */] <-2.6775427f ? 
                11.497414f : 
                -0.10017305f)) : 
         (data[14 /* V14 */] <-8.09046f ? 
             (data[4 /* V4 */] <5.4639077f ? 
                34.69278f : 
                57.8884f) : 
             (data[14 /* V14 */] <-4.6724534f ? 
                 (data[10 /* V10 */] <-1.8191738f ? 
                     (Double.isNaN(data[16]) || data[16 /* V16 */] <2.719751f ? 
                        50.63974f : 
                        -0.10017305f) : 
                     (Double.isNaN(data[21]) || data[21 /* V21 */] <-0.15561928f ? 
                        0.22198127f : 
                        12.325815f)) : 
                 (data[14 /* V14 */] <-4.197478f ? 
                     (data[7 /* V7 */] <0.2213662f ? 
                        24.751877f : 
                        0.36372918f) : 
                     (Double.isNaN(data[4]) || data[4 /* V4 */] <2.4237952f ? 
                        -0.090457395f : 
                        0.016851952f)))));
    return pred;
  } // constant pool size = 74B, number of visited nodes = 18, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_1_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[17 /* V17 */] <-2.745134f ? 
         (Double.isNaN(data[27]) || data[27 /* V27 */] <0.9255097f ? 
             (Double.isNaN(data[16]) || data[16 /* V16 */] <-0.74117756f ? 
                 (data[2 /* V2 */] <0.4029305f ? 
                     (data[4 /* V4 */] <2.2166033f ? 
                        -62.028038f : 
                        -12.35532f) : 
                     (data[4 /* V4 */] <2.7115068f ? 
                        -19.852514f : 
                        -16.539732f)) : 
                -27.077673f) : 
             (data[26 /* V26 */] <-0.2690587f ? 
                 (Double.isNaN(data[24]) || data[24 /* V24 */] <0.01285247f ? 
                     (Double.isNaN(data[19]) || data[19 /* V19 */] <1.7251849f ? 
                        -191.73898f : 
                        -83.02912f) : 
                    -126.33307f) : 
                 (Double.isNaN(data[14]) || data[14 /* V14 */] <-4.6491623f ? 
                     (Double.isNaN(data[25]) || data[25 /* V25 */] <1.0535747f ? 
                        0.0f : 
                        -240.72702f) : 
                    -120.57176f))) : 
         (data[14 /* V14 */] <-4.1695156f ? 
             (Double.isNaN(data[8]) || data[8 /* V8 */] <1.3465177f ? 
                 (data[8 /* V8 */] <-4.868939f ? 
                     (Double.isNaN(data[14]) || data[14 /* V14 */] <-4.6877785f ? 
                        -30.30365f : 
                        -0.1002218f) : 
                     (data[2 /* V2 */] <1.6827661f ? 
                        -8.452179f : 
                        -0.5966037f)) : 
                -66.680275f) : 
             (data[14 /* V14 */] <-1.8158143f ? 
                 (Double.isNaN(data[21]) || data[21 /* V21 */] <6.0096154f ? 
                     (Double.isNaN(data[4]) || data[4 /* V4 */] <2.552674f ? 
                        -0.020942327f : 
                        0.8295322f) : 
                    11.437785f) : 
                 (data[17 /* V17 */] <-1.9910431f ? 
                     (Double.isNaN(data[25]) || data[25 /* V25 */] <-0.32221502f ? 
                        -0.1001667f : 
                        6.1056166f) : 
                     (data[23 /* V23 */] <-15.348171f ? 
                        2.1027946f : 
                        -0.08782273f)))));
    return pred;
  } // constant pool size = 90B, number of visited nodes = 22, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_2_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[8]) || data[8 /* V8 */] <12.359933f ? 
         (data[14 /* V14 */] <-15.351469f ? 
            1.8062306E7f : 
             (Double.isNaN(data[8]) || data[8 /* V8 */] <10.352164f ? 
                 (data[17 /* V17 */] <-4.728106f ? 
                     (data[0 /* Time */] <16199.5f ? 
                        1291.2f : 
                        29.026945f) : 
                     (data[14 /* V14 */] <-11.26259f ? 
                        419430.38f : 
                        -0.08786611f)) : 
                22.150894f)) : 
         (data[0 /* Time */] <27336.5f ? 
            0.0f : 
            415.49338f));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_3_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[11 /* V11 */] <-4.04205f ? 
        -113.49397f : 
         (Double.isNaN(data[8]) || data[8 /* V8 */] <12.268894f ? 
             (Double.isNaN(data[17]) || data[17 /* V17 */] <7.1025057f ? 
                 (data[17 /* V17 */] <-2.9804022f ? 
                     (Double.isNaN(data[14]) || data[14 /* V14 */] <-3.879075f ? 
                        -0.10059267f : 
                        -3.9075496f) : 
                     (Double.isNaN(data[21]) || data[21 /* V21 */] <5.878919f ? 
                        -0.08277733f : 
                        -1.2676555f)) : 
                -32.100624f) : 
             (data[1 /* V1 */] <-26.286495f ? 
                0.0f : 
                0.0f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_4_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[8]) || data[8 /* V8 */] <10.948829f ? 
         (data[17 /* V17 */] <-3.0476215f ? 
             (Double.isNaN(data[3]) || data[3 /* V3 */] <-1.4377192f ? 
                 (Double.isNaN(data[17]) || data[17 /* V17 */] <-3.5798934f ? 
                     (data[2 /* V2 */] <-0.9007831f ? 
                        230611.72f : 
                        -0.1298987f) : 
                     (data[18 /* V18 */] <-0.5238245f ? 
                        -5.2472052E7f : 
                        0.10001025f)) : 
                 (Double.isNaN(data[23]) || data[23 /* V23 */] <0.13960135f ? 
                     (data[2 /* V2 */] <1.2295576f ? 
                        -3173.2378f : 
                        -0.6705081f) : 
                    -2.2887409f)) : 
             (Double.isNaN(data[21]) || data[21 /* V21 */] <6.121237f ? 
                 (data[14 /* V14 */] <-4.6747985f ? 
                     (data[24 /* V24 */] <-1.6576515f ? 
                        -10.86807f : 
                        -0.24313313f) : 
                     (data[17 /* V17 */] <-2.6553762f ? 
                        8.883559f : 
                        -0.08034429f)) : 
                 (data[14 /* V14 */] <-1.8940245f ? 
                    -3.4379492f : 
                     (Double.isNaN(data[9]) || data[9 /* V9 */] <3.4341547f ? 
                        -0.07447864f : 
                        -3.434629f)))) : 
         (data[0 /* Time */] <27336.5f ? 
            1.4E19f : 
            -3898442.0f));
    return pred;
  } // constant pool size = 62B, number of visited nodes = 15, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_5_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[8]) || data[8 /* V8 */] <17.321558f ? 
         (data[17 /* V17 */] <-2.442647f ? 
             (data[2 /* V2 */] <-0.5250087f ? 
                 (data[12 /* V12 */] <-2.9567075f ? 
                    -35115.453f : 
                     (Double.isNaN(data[14]) || data[14 /* V14 */] <-3.425028f ? 
                        0.7144784f : 
                        -0.80051273f)) : 
                 (Double.isNaN(data[14]) || data[14 /* V14 */] <-2.4864593f ? 
                     (data[2 /* V2 */] <0.59775406f ? 
                        16.981672f : 
                        -1.1189947f) : 
                     (data[28 /* V28 */] <0.12311632f ? 
                        -0.12206361f : 
                        -0.20880152f))) : 
             (Double.isNaN(data[8]) || data[8 /* V8 */] <10.352893f ? 
                 (Double.isNaN(data[18]) || data[18 /* V18 */] <3.2736394f ? 
                     (data[14 /* V14 */] <-4.9117556f ? 
                        0.82025474f : 
                        -0.08028482f) : 
                     (Double.isNaN(data[3]) || data[3 /* V3 */] <-4.1535378f ? 
                        -0.05542059f : 
                        -20.588856f)) : 
                -400277.4f)) : 
        1.50000008E18f);
    return pred;
  } // constant pool size = 50B, number of visited nodes = 12, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_6_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[8]) || data[8 /* V8 */] <17.321558f ? 
         (data[17 /* V17 */] <-4.2575703f ? 
             (Double.isNaN(data[7]) || data[7 /* V7 */] <0.6854332f ? 
                 (Double.isNaN(data[14]) || data[14 /* V14 */] <-2.4864593f ? 
                     (data[4 /* V4 */] <1.298068f ? 
                        -2.6787925f : 
                        35696.098f) : 
                     (data[18 /* V18 */] <-2.1272185f ? 
                        -0.1206566f : 
                        -0.30041876f)) : 
                -6.3646125E11f) : 
             (data[17 /* V17 */] <-3.149238f ? 
                 (data[3 /* V3 */] <-4.211172f ? 
                    3355094.2f : 
                     (Double.isNaN(data[18]) || data[18 /* V18 */] <-0.31016567f ? 
                        0.09654374f : 
                        0.1027069f)) : 
                 (data[17 /* V17 */] <-2.664755f ? 
                     (Double.isNaN(data[17]) || data[17 /* V17 */] <-2.7461379f ? 
                        0.1109512f : 
                        -0.5990374f) : 
                     (data[14 /* V14 */] <-3.9332588f ? 
                        -0.5990198f : 
                        -0.07655451f)))) : 
        0.0f);
    return pred;
  } // constant pool size = 50B, number of visited nodes = 12, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_7_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[17 /* V17 */] <-6.8791265f ? 
         (data[22 /* V22 */] <-0.17315917f ? 
             (Double.isNaN(data[9]) || data[9 /* V9 */] <-3.4553266f ? 
                 (Double.isNaN(data[20]) || data[20 /* V20 */] <1.6986303f ? 
                    0.0f : 
                    -5.0E18f) : 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <32180.0f ? 
                     (Double.isNaN(data[0]) || data[0 /* Time */] <25085.0f ? 
                        0.0f : 
                        0.0f) : 
                    0.0f)) : 
             (Double.isNaN(data[3]) || data[3 /* V3 */] <-3.691944f ? 
                 (Double.isNaN(data[16]) || data[16 /* V16 */] <-4.79463f ? 
                     (data[11 /* V11 */] <3.1660914f ? 
                        0.0f : 
                        0.0f) : 
                    1.00000005E18f) : 
                -8892.718f)) : 
         (data[17 /* V17 */] <-5.1461267f ? 
             (Double.isNaN(data[14]) || data[14 /* V14 */] <-2.8869603f ? 
                 (data[4 /* V4 */] <1.7180862f ? 
                    8.8305094E12f : 
                    0.0f) : 
                 (data[3 /* V3 */] <-3.7504666f ? 
                    -0.11775741f : 
                    -0.7477472f)) : 
             (Double.isNaN(data[11]) || data[11 /* V11 */] <4.273168f ? 
                 (data[27 /* V27 */] <-6.2780523f ? 
                     (Double.isNaN(data[16]) || data[16 /* V16 */] <2.1593375f ? 
                        -0.10020241f : 
                        -1.0538055f) : 
                     (data[14 /* V14 */] <-8.507492f ? 
                        -0.6433459f : 
                        -0.076069795f)) : 
                 (Double.isNaN(data[19]) || data[19 /* V19 */] <0.8899523f ? 
                     (Double.isNaN(data[20]) || data[20 /* V20 */] <2.8687987f ? 
                        -0.10008624f : 
                        -0.110589996f) : 
                    0.0f))));
    return pred;
  } // constant pool size = 78B, number of visited nodes = 19, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_8_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
         (Double.isNaN(data[8]) || data[8 /* V8 */] <17.27604f ? 
             (data[17 /* V17 */] <-4.862545f ? 
                 (Double.isNaN(data[15]) || data[15 /* V15 */] <0.93533415f ? 
                     (Double.isNaN(data[14]) || data[14 /* V14 */] <-2.801296f ? 
                        3.00194894E14f : 
                        -0.5076225f) : 
                     (data[0 /* Time */] <32028.5f ? 
                        0.0f : 
                        -3344370.0f)) : 
                 (data[17 /* V17 */] <-4.4214177f ? 
                     (Double.isNaN(data[19]) || data[19 /* V19 */] <0.78990936f ? 
                        -1.2089204f : 
                        2.60171392E8f) : 
                     (data[27 /* V27 */] <-6.105805f ? 
                        -0.47084317f : 
                        -0.07405615f))) : 
            1.25E18f) : 
         (data[4 /* V4 */] <6.3450994f ? 
             (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                0.0f : 
                0.0f) : 
            0.0f));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_9_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
         (data[14 /* V14 */] <-12.534198f ? 
             (data[15 /* V15 */] <0.7263234f ? 
                0.0f : 
                9.0000002E18f) : 
             (Double.isNaN(data[8]) || data[8 /* V8 */] <17.27604f ? 
                 (data[16 /* V16 */] <-5.7772856f ? 
                     (Double.isNaN(data[15]) || data[15 /* V15 */] <0.93533415f ? 
                        0.0f : 
                        1.1E19f) : 
                     (data[12 /* V12 */] <-6.9946437f ? 
                        -1.09151709E12f : 
                        -0.06995812f)) : 
                1.25E18f)) : 
         (data[4 /* V4 */] <6.3450994f ? 
             (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                0.0f : 
                0.0f) : 
            0.0f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_10_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <3.732219f ? 
             (data[10 /* V10 */] <-6.2744355f ? 
                 (Double.isNaN(data[10]) || data[10 /* V10 */] <-6.7036657f ? 
                     (data[18 /* V18 */] <-4.2755623f ? 
                        2.50000013E17f : 
                        -0.1001319f) : 
                    183.90703f) : 
                 (data[18 /* V18 */] <-3.7852135f ? 
                    -22.243387f : 
                     (data[12 /* V12 */] <-4.8625274f ? 
                        0.59828955f : 
                        -0.07191615f))) : 
             (data[0 /* Time */] <14849.5f ? 
                 (data[9 /* V9 */] <-1.836686f ? 
                    0.0f : 
                     (data[8 /* V8 */] <0.5374608f ? 
                        -0.10006547f : 
                        0.0f)) : 
                 (Double.isNaN(data[8]) || data[8 /* V8 */] <15.974037f ? 
                     (Double.isNaN(data[28]) || data[28 /* V28 */] <0.5694578f ? 
                        1.3951719f : 
                        190.68686f) : 
                    5.0E18f))) : 
         (data[4 /* V4 */] <6.3450994f ? 
             (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                0.0f : 
                0.0f) : 
            0.0f));
    return pred;
  } // constant pool size = 58B, number of visited nodes = 14, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_11_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
         (data[12 /* V12 */] <-7.1277385f ? 
             (Double.isNaN(data[17]) || data[17 /* V17 */] <-5.064203f ? 
                 (Double.isNaN(data[11]) || data[11 /* V11 */] <7.152213f ? 
                     (Double.isNaN(data[25]) || data[25 /* V25 */] <1.0885522f ? 
                        -1.11111113E17f : 
                        0.0f) : 
                    0.0f) : 
                 (data[9 /* V9 */] <-2.635761f ? 
                    0.0f : 
                    0.0f)) : 
             (Double.isNaN(data[10]) || data[10 /* V10 */] <13.172205f ? 
                 (data[18 /* V18 */] <-3.8060021f ? 
                     (Double.isNaN(data[3]) || data[3 /* V3 */] <-5.2506647f ? 
                        -3.4720953f : 
                        -1.77525398E12f) : 
                     (data[16 /* V16 */] <-4.8435006f ? 
                        0.0f : 
                        -0.069550164f)) : 
                -66.16494f)) : 
         (data[4 /* V4 */] <6.3450994f ? 
             (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                0.0f : 
                0.0f) : 
            0.0f));
    return pred;
  } // constant pool size = 50B, number of visited nodes = 12, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_12_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[12 /* V12 */] <-7.1277385f ? 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4206824f ? 
             (Double.isNaN(data[15]) || data[15 /* V15 */] <0.93533415f ? 
                 (Double.isNaN(data[8]) || data[8 /* V8 */] <10.305745f ? 
                     (Double.isNaN(data[11]) || data[11 /* V11 */] <7.1227927f ? 
                        0.0f : 
                        0.0f) : 
                    0.0f) : 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <69178.5f ? 
                     (Double.isNaN(data[1]) || data[1 /* V1 */] <-5.2620096f ? 
                        -0.1f : 
                        2.85714298E17f) : 
                    0.0f)) : 
             (data[4 /* V4 */] <6.378699f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)) : 
         (Double.isNaN(data[10]) || data[10 /* V10 */] <13.172205f ? 
             (data[18 /* V18 */] <-3.785895f ? 
                 (Double.isNaN(data[3]) || data[3 /* V3 */] <-5.2506647f ? 
                     (data[26 /* V26 */] <-0.22138432f ? 
                        -8.397593E11f : 
                        -0.10005068f) : 
                    -3.00000016E18f) : 
                 (data[16 /* V16 */] <-4.974835f ? 
                     (data[5 /* V5 */] <-2.4707794f ? 
                        0.0f : 
                        0.0f) : 
                     (data[12 /* V12 */] <-4.2983856f ? 
                        0.59643567f : 
                        -0.07002792f))) : 
            -6.6666668E17f));
    return pred;
  } // constant pool size = 66B, number of visited nodes = 16, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_13_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-4.362485f ? 
         (data[24 /* V24 */] <-0.47402593f ? 
             (data[27 /* V27 */] <0.55399024f ? 
                -0.10006309f : 
                0.0f) : 
             (data[14 /* V14 */] <-13.521695f ? 
                0.0f : 
                 (data[11 /* V11 */] <3.7501597f ? 
                    40.201366f : 
                     (Double.isNaN(data[3]) || data[3 /* V3 */] <-13.066013f ? 
                        0.0f : 
                        0.0f)))) : 
         (data[10 /* V10 */] <-9.672877f ? 
             (data[16 /* V16 */] <-10.253948f ? 
                0.0f : 
                0.0f) : 
             (data[12 /* V12 */] <-8.592442f ? 
                 (data[14 /* V14 */] <-11.361558f ? 
                    0.0f : 
                     (data[6 /* V6 */] <-2.4349666f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.0494895f ? 
                     (Double.isNaN(data[15]) || data[15 /* V15 */] <0.87681365f ? 
                        1.9E19f : 
                        -3.50000005E18f) : 
                     (data[16 /* V16 */] <-4.3181653f ? 
                        213.3477f : 
                        -0.065450594f)))));
    return pred;
  } // constant pool size = 58B, number of visited nodes = 14, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_14_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[21 /* V21 */] <-14.475732f ? 
                    -89.18827f : 
                     (data[12 /* V12 */] <-4.1761594f ? 
                        1.4074733f : 
                        -0.06883264f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 42B, number of visited nodes = 10, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_15_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.058896575f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_16_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.056264978f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_17_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.053605493f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_18_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.050932407f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_19_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.04826029f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_20_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.04560365f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_21_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.04297662f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_22_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.04039273f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_23_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.037864592f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_24_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.035403706f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_25_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.033020265f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_26_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.030723007f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_27_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.028519241f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_28_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.026414594f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_29_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.024413306f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_30_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.022518132f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_31_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.020730402f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_32_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.019050252f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_33_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.017476616f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_34_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.016007563f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_35_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.014640366f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_36_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.013371486f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_37_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.012197037f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_38_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.011112566f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_39_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.010113545f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_40_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.009195057f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_41_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.008352263f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_42_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.007580311f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_43_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.0068743364f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_44_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.0062297573f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_45_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.00564197f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_46_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.0051066047f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_47_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.004619519f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_48_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.0041768746f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_49_class_0.score0(fdata);
  }
}
class gbm_a65d8149_cfdc_4f33_bead_5d9456e4a93b_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[9 /* V9 */] <-7.2824f ? 
         (Double.isNaN(data[28]) || data[28 /* V28 */] <-0.608218f ? 
            0.0f : 
            0.0f) : 
         (Double.isNaN(data[11]) || data[11 /* V11 */] <7.4699492f ? 
             (data[12 /* V12 */] <-8.526893f ? 
                 (data[14 /* V14 */] <-13.308699f ? 
                    0.0f : 
                     (Double.isNaN(data[27]) || data[27 /* V27 */] <1.0720061f ? 
                        0.0f : 
                        0.0f)) : 
                 (data[12 /* V12 */] <-7.8872333f ? 
                     (data[14 /* V14 */] <-8.451234f ? 
                        -0.1f : 
                        0.0f) : 
                     (data[17 /* V17 */] <-11.678484f ? 
                        0.0f : 
                        -0.003774953f))) : 
             (data[4 /* V4 */] <6.3450994f ? 
                 (Double.isNaN(data[0]) || data[0 /* Time */] <23849.5f ? 
                    0.0f : 
                    0.0f) : 
                0.0f)));
    return pred;
  } // constant pool size = 46B, number of visited nodes = 11, static init size = 0B
}


